### ISSUE TITLE
Final todo

### ISSUE THREAD

**Issue by alexandervice** [alexandervice/rise-character-planner#1]
- [x] Delete images from the S3 Bucket when updating and deleting characters (still not working)
- [x] Add Map route to view Map of Elara
- [x] Deploy using Docker on an ECS Cluster.

**Comment by alexandervice** [comment]
done

**Comment by alexandervice** [comment]
Done
